version: "2"

networks:
  test:

services:
  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - TZ=Asia/Seoul
    ports:
      - 9984:5984
    volumes:
      - /home/fabric/Hyperledger_Fabric_NFT_TEST/couchdb/data5/:/opt/couchdb/data/
    networks:
      - test

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - TZ=Asia/Seoul
    ports:
      - 10984:5984
    volumes:
      - /home/fabric/Hyperledger_Fabric_NFT_TEST/couchdb/data6/:/opt/couchdb/data/
    networks:
      - test

  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.example.com:12051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9640
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - TZ=Asia/Seoul 
    depends_on:
      - couchdb4
    ports:
      - 11051:11051
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test
    extra_hosts:
                - "orderer.example.com:211.232.75.182"
                - "orderer2.example.com:211.232.75.182"
                - "orderer3.example.com:211.232.75.182"
                - "peer0.org1.example.com:211.232.75.182"
                - "peer1.org1.example.com:211.232.75.182"
                - "peer0.org2.example.com:211.232.75.182"
                - "peer1.org2.example.com:211.232.75.182"
                - "peer0.org3.example.com:211.232.75.182"
                - "peer1.org3.example.com:211.232.75.182"
                - "peer0.org4.example.com:211.232.75.182"
                - "peer1.org4.example.com:211.232.75.182"

  peer1.org3.example.com:
    container_name: peer1.org3.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test
      - CORE_PEER_ID=peer1.org3.example.com
      - CORE_PEER_ADDRESS=peer1.org3.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:11051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9641
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - TZ=Asia/Seoul
    ports:
      - 12051:12051
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test
    extra_hosts:
                - "orderer.example.com:211.232.75.182"
                - "orderer2.example.com:211.232.75.182"
                - "orderer3.example.com:211.232.75.182"
                - "peer0.org1.example.com:211.232.75.182"
                - "peer1.org1.example.com:211.232.75.182"
                - "peer0.org2.example.com:211.232.75.182"
                - "peer1.org2.example.com:211.232.75.182"
                - "peer0.org3.example.com:211.232.75.182"
                - "peer1.org3.example.com:211.232.75.182"
                - "peer0.org4.example.com:211.232.75.182"
                - "peer1.org4.example.com:211.232.75.182"

  prometheus_org3:
      container_name: prometheus_org3
      image: prom/prometheus:latest
      ports:
        - 11090:11090
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.listen-address=0.0.0.0:11090'
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      environment:
        - TZ=Asia/Seoul
      networks:
        - test
      depends_on:
        - peer0.org3.example.com
        - peer1.org3.example.com
