global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:11090']

  - job_name: 'fabric_1.0_org3_metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['peer0.org3.example.com:9640', 'peer1.org3.example.com:9641']