global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:10090']

  - job_name: 'fabric_1.0_org2_metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['peer0.org2.example.com:9540', 'peer1.org2.example.com:9541']