# SPDX-License-Identifier: Apache-2.0
version: '2.1'


networks:
  artifacts_test:

services:
  testexplorer:
    image: testexplorer
    container_name: testexplorer
    hostname: testexplorer
    environment:
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    ports:
      - 3356:3356
    networks:
      - artifacts_test
