version: '2'

networks:
  test:

services:
  ca_org4:
    image: hyperledger/fabric-ca:1.5.2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org4.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=20054
    ports:
      - "20054:20054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org4:/etc/hyperledger/fabric-ca-server
    container_name: ca.org4.example.com
    hostname: ca.org4.example.com
    networks:
      - test
